baseurl             = "https://hye-rim.github.io/"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "en-US"
layoutdir           = "layouts"
publishdir          = "public"
theme = "cocoa-eh"
author              = "hyerim"
title               = "hyerim blog"
pygmentsuseclasses  = true
disqusshortname     = "hyerims-blog"
googleAnalytics     = "UA-111392347-1"
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "hyerim blog"
copyright = "Copyright © 2015 Nishanth Shanmugham"
logofile = "img/profile.jpeg"
faviconfile = "img/profile.jpeg"
avator = "imag/profile.jpeg"
highlightjs = true
progressively = true
align_left = false
lang = "en"
latestpostcount = 5
github = "hye-rim"
email = "phl2898@gmail.com"
# linkedin = "john-example-aa80ue8è"
# twitter = "example"
social_banner = "img/banner.png"
usesmallsummarycard = true
posts_navigation = true
small_banner_logo = false


[params.colors]
identifier = "#527fc1f"
identifier_dark = "#1a3152"
trivial = "#6a7a8b"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"
